// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pelhygeorscmqhtiruuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlbGh5Z2VvcnNjbXFodGlydXV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0MzQ5NDQsImV4cCI6MjA4OTAxMDk0NH0.HSPeG4pbUHZnG-yadZvLrs3lpumwLHLI5HvLzJZwT7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});